server:
  port: ${SERVER_PORT}

spring:
  application:
    name: feed-service
  cloud:
    compatibility-verifier:
      enabled: false
  profiles:
    include:
      - security
      - openapi
      - jwt
      - database
      - openfeign